// Full-scale dry-run parity test against meow-tower. Walks every .tpsheet
// under $MEOW_TOWER_PATH/Assets (or ~/Develop/meow-tower as fallback),
// filters legacy atlases, and asserts byte-exact equality between
// pipeline-generated bytes and the committed .asset / .asset.meta for every
// sprite. Reports drift atlases via stderr.
//
// Run:
//   cargo test --test e2e_meow_tower -- --nocapture
//   MEOW_TOWER_PATH=/path/to/meow-tower cargo test --test e2e_meow_tower
//
// The test is opt-out and skips cleanly in two scenarios:
//   1. Neither `MEOW_TOWER_PATH` nor the default checkout exists.
//   2. The checkout exists but carries no `.tpsheet` files (the
//      post-rlib-pivot state — `pipeline::generate` deletes `.tpsheet`s
//      on success, so they're only present mid-import).
// Both print a skip notice and pass; the panic fires only if tpsheets
// were found yet zero sprites compared (genuine wiring bug).

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use unity_sprite_author::{
    emit::{self, SpriteAsset},
    meta,
    render_data::{self, AtlasSize},
    tps, tpsheet,
};

fn meow_tower_root() -> Option<PathBuf> {
    if let Ok(p) = std::env::var("MEOW_TOWER_PATH") {
        let path = PathBuf::from(p);
        if path.exists() {
            return Some(path);
        }
    }
    let default = PathBuf::from("/Users/jameskim/Develop/meow-tower");
    if default.exists() {
        Some(default)
    } else {
        None
    }
}

fn find_tpsheets(root: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(root) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            find_tpsheets(&path, out);
        } else if path.extension().is_some_and(|e| e == "tpsheet") {
            out.push(path);
        }
    }
}

fn extract_ppu(meta_text: &str) -> Option<f32> {
    for line in meta_text.lines() {
        if let Some(rest) = line.trim_start().strip_prefix("spritePixelsToUnits: ") {
            return rest.trim().parse().ok();
        }
    }
    None
}

// Mirrors TPSheetPostprocessor.IsLegacyTexture: textureType=Sprite (8) AND
// spriteMode=Multiple (2). YAML values are numeric.
fn is_legacy_texture(meta_text: &str) -> bool {
    let mut texture_type: Option<i32> = None;
    let mut sprite_mode: Option<i32> = None;
    for line in meta_text.lines() {
        let t = line.trim_start();
        if let Some(rest) = t.strip_prefix("textureType: ") {
            texture_type = rest.trim().parse().ok();
        } else if let Some(rest) = t.strip_prefix("spriteMode: ") {
            sprite_mode = rest.trim().parse().ok();
        }
    }
    texture_type == Some(8) && sprite_mode == Some(2)
}

fn extract_prefix(tpsheet_meta_path: &Path) -> String {
    let Ok(text) = fs::read_to_string(tpsheet_meta_path) else {
        return String::new();
    };
    for line in text.lines() {
        if let Some(rest) = line.trim_start().strip_prefix("_prefix: ") {
            return rest.trim_end().to_string();
        }
        // Also handle `_prefix:` (no value, no space).
        if line.trim_end() == "  _prefix:" || line.trim_end() == "_prefix:" {
            return String::new();
        }
    }
    String::new()
}

fn first_diff_offset(a: &[u8], b: &[u8]) -> usize {
    a.iter()
        .zip(b.iter())
        .position(|(x, y)| x != y)
        .unwrap_or_else(|| a.len().min(b.len()))
}

#[derive(Default)]
struct Stats {
    atlases_total: usize,
    atlases_legacy: usize,
    atlases_no_meta: usize,
    atlases_parse_failed: usize,
    sprites_compared: usize,
    sprites_byte_exact: usize,
    sprites_mismatch_asset: usize,
    sprites_mismatch_meta: usize,
    sprites_missing_golden: usize,
    drift_atlases: BTreeMap<String, usize>, // atlas → mismatch count
    parse_failures: Vec<(PathBuf, String)>, // for diagnosis
}

#[test]
fn e2e_meow_tower_byte_exact() {
    let Some(meow_root) = meow_tower_root() else {
        eprintln!("e2e: MEOW_TOWER_PATH not set and default not found; skipping.");
        return;
    };
    let assets_root = meow_root.join("Assets");
    let mut tpsheets = Vec::new();
    find_tpsheets(&assets_root, &mut tpsheets);
    tpsheets.sort();

    // `.tpsheet` files are ephemeral by design — `pipeline::generate`
    // deletes each one on success after re-emitting the per-sprite
    // `.asset`s. In a quiesced meow-tower checkout (all imports
    // settled, TexturePacker not re-run since), the `.tps` files are
    // present but no `.tpsheet` siblings exist. Skip cleanly in that
    // case — only panic if we found tpsheets but compared none of
    // them, which would be a real wiring bug rather than a fixture-
    // state quirk.
    if tpsheets.is_empty() {
        eprintln!(
            "e2e: no .tpsheet files under {}; skipping (run TexturePacker via Unity first).",
            assets_root.display()
        );
        return;
    }

    let mut stats = Stats::default();
    let mut first_mismatches: Vec<(PathBuf, String, &'static str, usize)> = Vec::new();

    for tpsheet_path in &tpsheets {
        stats.atlases_total += 1;
        let base = tpsheet_path.file_stem().unwrap().to_string_lossy().to_string();
        let parent = tpsheet_path.parent().unwrap();
        let png_meta_path = parent.join(format!("{base}.png.meta"));
        let tps_path = parent.join(format!("{base}.tps"));
        // Every non-legacy atlas should have a same-stem .tps. The earlier
        // exception was Unity's native SpriteAtlas (Tower_SpriteAtlas.tpsheet
        // paired with Tower.tps under a different stem), but that case has
        // been consolidated. If a missing .tps shows up again, fail loudly
        // rather than silently skip — the caller wants to know.
        assert!(
            tps_path.exists(),
            "missing .tps for {tpsheet_path:?} (stem mismatch?)"
        );
        let tpsheet_meta_path = parent.join(format!("{base}.tpsheet.meta"));
        let sprite_dir = parent.join(&base);

        let Ok(png_meta_text) = fs::read_to_string(&png_meta_path) else {
            stats.atlases_no_meta += 1;
            continue;
        };
        if is_legacy_texture(&png_meta_text) {
            stats.atlases_legacy += 1;
            continue;
        }
        let Some(ppu) = extract_ppu(&png_meta_text) else {
            stats.atlases_parse_failed += 1;
            stats.parse_failures.push((tpsheet_path.clone(), "no spritePixelsToUnits in .png.meta".into()));
            continue;
        };
        let Ok(atlas_guid) = meta::parse_guid(&png_meta_text) else {
            stats.atlases_parse_failed += 1;
            stats.parse_failures.push((tpsheet_path.clone(), "no guid in .png.meta".into()));
            continue;
        };
        let prefix = extract_prefix(&tpsheet_meta_path);

        let Ok(tpsheet_text) = fs::read_to_string(tpsheet_path) else {
            stats.atlases_parse_failed += 1;
            stats.parse_failures.push((tpsheet_path.clone(), "tpsheet read failed".into()));
            continue;
        };
        let sheet = match tpsheet::parse(&tpsheet_text) {
            Ok(s) => s,
            Err(e) => {
                stats.atlases_parse_failed += 1;
                stats.parse_failures.push((tpsheet_path.clone(), format!("tpsheet: {e}")));
                continue;
            }
        };
        let tps_data = match tps::parse(&tps_path) {
            Ok(d) => d,
            Err(e) => {
                stats.atlases_parse_failed += 1;
                stats.parse_failures.push((tpsheet_path.clone(), format!("tps: {e}")));
                continue;
            }
        };
        let atlas_size = AtlasSize {
            width: sheet.tex.width,
            height: sheet.tex.height,
        };

        let atlas_label = parent
            .strip_prefix(&assets_root)
            .map(|p| p.join(&base).to_string_lossy().into_owned())
            .unwrap_or_else(|_| base.clone());

        for sprite in &sheet.sprites {
            let asset_name = format!("{prefix}{}", sprite.name);
            let asset_path = sprite_dir.join(format!("{asset_name}.asset"));
            let meta_path = sprite_dir.join(format!("{asset_name}.asset.meta"));

            let Ok(golden_asset) = fs::read(&asset_path) else {
                stats.sprites_missing_golden += 1;
                continue;
            };
            let Ok(golden_meta) = fs::read(&meta_path) else {
                stats.sprites_missing_golden += 1;
                continue;
            };

            let Ok(golden_meta_text) = std::str::from_utf8(&golden_meta) else {
                continue;
            };
            let Ok(own_guid) = meta::parse_guid(golden_meta_text) else {
                continue;
            };
            let meta_shape = meta::detect_shape(golden_meta_text);

            let invert_scale = tps_data.invert_scale(&sprite.name);
            let pixels_to_units = ppu / invert_scale;
            let rd = render_data::build(
                sprite.rect,
                sprite.pivot,
                &sprite.geometry.vertices,
                &sprite.geometry.triangles,
                ppu,
                invert_scale,
                atlas_size,
            );
            let asset = SpriteAsset {
                name: asset_name.clone(),
                rect: sprite.rect,
                border: sprite.border,
                pivot: sprite.pivot,
                pixels_to_units,
                own_guid,
                atlas_guid,
                render_data: rd,
                source: emit::SpriteSource::Tpsheet,
            };

            let generated_asset = match emit::emit(&asset) {
                Ok(s) => s.into_bytes(),
                Err(e) => match e {}, // EmitError is uninhabited
            };
            let generated_meta = meta::render_asset_meta_with_shape(&own_guid, meta_shape).into_bytes();

            stats.sprites_compared += 1;
            let asset_match = generated_asset == golden_asset;
            let meta_match = generated_meta == golden_meta;

            if asset_match && meta_match {
                stats.sprites_byte_exact += 1;
            } else {
                if !asset_match {
                    stats.sprites_mismatch_asset += 1;
                    if first_mismatches.len() < 12 {
                        first_mismatches.push((
                            tpsheet_path.clone(),
                            asset_name.clone(),
                            "asset",
                            first_diff_offset(&generated_asset, &golden_asset),
                        ));
                    }
                }
                if !meta_match {
                    stats.sprites_mismatch_meta += 1;
                    if stats.sprites_mismatch_meta <= 3 {
                        // Metas only carry GUID variation; mismatches are
                        // structurally interesting. Dump the diff window.
                        let off = first_diff_offset(&generated_meta, &golden_meta);
                        let lo = off.saturating_sub(8);
                        let hi_g = (off + 24).min(generated_meta.len());
                        let hi_e = (off + 24).min(golden_meta.len());
                        eprintln!(
                            "  META DIFF {} :: {asset_name}\n    generated[{lo}..{hi_g}]: {:?}\n    golden   [{lo}..{hi_e}]: {:?}",
                            tpsheet_path.display(),
                            String::from_utf8_lossy(&generated_meta[lo..hi_g]),
                            String::from_utf8_lossy(&golden_meta[lo..hi_e]),
                        );
                    }
                }
                *stats.drift_atlases.entry(atlas_label.clone()).or_insert(0) += 1;
            }
        }
    }

    eprintln!();
    eprintln!("=== meow-tower e2e parity report ===");
    eprintln!("atlases scanned:        {}", stats.atlases_total);
    eprintln!("  legacy (skipped):     {}", stats.atlases_legacy);
    eprintln!("  no .png.meta:         {}", stats.atlases_no_meta);
    eprintln!("  parse failed:         {}", stats.atlases_parse_failed);
    for (p, why) in &stats.parse_failures {
        eprintln!("    {} — {why}", p.display());
    }
    eprintln!("sprites compared:       {}", stats.sprites_compared);
    eprintln!("  byte-exact:           {}", stats.sprites_byte_exact);
    eprintln!("  mismatch (.asset):    {}", stats.sprites_mismatch_asset);
    eprintln!("  mismatch (.meta):     {}", stats.sprites_mismatch_meta);
    eprintln!("  golden missing:       {}", stats.sprites_missing_golden);
    eprintln!("drift atlases:          {}", stats.drift_atlases.len());
    for (atlas, n) in stats.drift_atlases.iter().take(10) {
        eprintln!("  {n:>4} mismatches  {atlas}");
    }
    if stats.drift_atlases.len() > 10 {
        eprintln!("  ... ({} more)", stats.drift_atlases.len() - 10);
    }
    for (path, name, kind, off) in first_mismatches.iter().take(8) {
        eprintln!(
            "  first divergence  {kind} @{off:<6}  {} :: {name}",
            path.display()
        );
    }
    eprintln!();

    // Hard parity gates. Anything outside the explicit allowlist below
    // counts as a regression. Allowlist owners: when the underlying gap
    // is fixed, remove the entry — the test will fail until it's gone,
    // forcing a confirmation.
    assert_eq!(stats.atlases_parse_failed, 0, "tpsheet/tps parse failures");
    assert!(
        stats.sprites_compared > 0,
        "no sprites compared — fixture path wrong?"
    );

    // 100% parity reached. Any future divergence is a regression.
    const ALLOWED_ASSET_MISMATCHES: usize = 0;
    const ALLOWED_META_MISMATCHES: usize = 0;
    assert_eq!(
        stats.sprites_mismatch_asset, ALLOWED_ASSET_MISMATCHES,
        ".asset mismatches changed (allowed {ALLOWED_ASSET_MISMATCHES}); regression or progress — \
         update the constant after auditing"
    );
    assert_eq!(
        stats.sprites_mismatch_meta, ALLOWED_META_MISMATCHES,
        ".meta mismatches changed (allowed {ALLOWED_META_MISMATCHES})"
    );
}
