// Full-scale dry-run parity test against meow-tower. Walks every .tpsheet
// under $MEOW_TOWER_PATH/Assets (or ~/Develop/meow-tower as fallback),
// filters legacy atlases, and asserts byte-exact equality between
// pipeline-generated bytes and the committed .asset / .asset.meta for every
// sprite. Reports drift atlases via stderr.
//
// Run:
//   cargo test --test e2e_meow_tower -- --nocapture
//   MEOW_TOWER_PATH=/path/to/meow-tower cargo test --test e2e_meow_tower
//
// The test is opt-out and skips cleanly in two scenarios:
//   1. Neither `MEOW_TOWER_PATH` nor the default checkout exists.
//   2. The checkout exists but carries no `.tpsheet` files (the
//      post-rlib-pivot state — `pipeline::generate` deletes `.tpsheet`s
//      on success, so they're only present mid-import).
// Both print a skip notice and pass; the panic fires only if tpsheets
// were found yet zero sprites compared (genuine wiring bug).

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use unity_sprite_author::pipeline::{self, GenerateInputs};

fn meow_tower_root() -> Option<PathBuf> {
    if let Ok(p) = std::env::var("MEOW_TOWER_PATH") {
        let path = PathBuf::from(p);
        if path.exists() {
            return Some(path);
        }
    }
    let default = PathBuf::from("/Users/jameskim/Develop/meow-tower");
    if default.exists() {
        Some(default)
    } else {
        None
    }
}

fn find_tpsheets(root: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(root) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            find_tpsheets(&path, out);
        } else if path.extension().is_some_and(|e| e == "tpsheet") {
            out.push(path);
        }
    }
}

// Mirrors TPSheetPostprocessor.IsLegacyTexture: textureType=Sprite (8) AND
// spriteMode=Multiple (2). YAML values are numeric.
fn is_legacy_texture(meta_text: &str) -> bool {
    let mut texture_type: Option<i32> = None;
    let mut sprite_mode: Option<i32> = None;
    for line in meta_text.lines() {
        let t = line.trim_start();
        if let Some(rest) = t.strip_prefix("textureType: ") {
            texture_type = rest.trim().parse().ok();
        } else if let Some(rest) = t.strip_prefix("spriteMode: ") {
            sprite_mode = rest.trim().parse().ok();
        }
    }
    texture_type == Some(8) && sprite_mode == Some(2)
}

fn extract_prefix(tps_meta_path: &Path) -> String {
    let Ok(text) = fs::read_to_string(tps_meta_path) else {
        return String::new();
    };
    for line in text.lines() {
        if let Some(rest) = line.trim_start().strip_prefix("_prefix: ") {
            return rest.trim_end().to_string();
        }
        // Also handle `_prefix:` (no value, no space).
        if line.trim_end() == "  _prefix:" || line.trim_end() == "_prefix:" {
            return String::new();
        }
    }
    String::new()
}

fn first_diff_offset(a: &[u8], b: &[u8]) -> usize {
    a.iter()
        .zip(b.iter())
        .position(|(x, y)| x != y)
        .unwrap_or_else(|| a.len().min(b.len()))
}

#[derive(Default)]
struct Stats {
    atlases_total: usize,
    atlases_legacy: usize,
    atlases_no_meta: usize,
    atlases_parse_failed: usize,
    sprites_compared: usize,
    sprites_byte_exact: usize,
    sprites_mismatch_asset: usize,
    sprites_mismatch_meta: usize,
    sprites_missing_golden: usize,
    drift_atlases: BTreeMap<String, usize>, // atlas → mismatch count
    parse_failures: Vec<(PathBuf, String)>, // for diagnosis
}

#[test]
fn e2e_meow_tower_byte_exact() {
    let Some(meow_root) = meow_tower_root() else {
        eprintln!("e2e: MEOW_TOWER_PATH not set and default not found; skipping.");
        return;
    };
    let assets_root = meow_root.join("Assets");
    let mut tpsheets = Vec::new();
    find_tpsheets(&assets_root, &mut tpsheets);
    tpsheets.sort();

    // `.tpsheet` files are produced by TexturePacker (via Unity import) and
    // are the pipeline's input — `generate` retains them on disk. But a
    // checkout that has never run a TP pack won't have any, so skip cleanly
    // in that case rather than failing.
    if tpsheets.is_empty() {
        eprintln!(
            "e2e: no .tpsheet files under {}; skipping (run TexturePacker via Unity first).",
            assets_root.display()
        );
        return;
    }

    let mut stats = Stats::default();
    let mut first_mismatches: Vec<(PathBuf, String, &'static str, usize)> = Vec::new();

    for tpsheet_path in &tpsheets {
        stats.atlases_total += 1;
        let base = tpsheet_path.file_stem().unwrap().to_string_lossy().to_string();
        let parent = tpsheet_path.parent().unwrap();
        let png_meta_path = parent.join(format!("{base}.png.meta"));
        let tps_path = parent.join(format!("{base}.tps"));
        // Every non-legacy atlas should have a same-stem .tps. The earlier
        // exception was Unity's native SpriteAtlas (Tower_SpriteAtlas.tpsheet
        // paired with Tower.tps under a different stem), but that case has
        // been consolidated. If a missing .tps shows up again, fail loudly
        // rather than silently skip — the caller wants to know.
        assert!(
            tps_path.exists(),
            "missing .tps for {tpsheet_path:?} (stem mismatch?)"
        );
        // _prefix moved from .tpsheet.meta to .tps.meta in the TPSImporter
        // migration (see scripts/migrate-tpsheet-meta.sh + CLAUDE.md "Migration").
        let tps_meta_path = parent.join(format!("{base}.tps.meta"));
        let sprite_dir = parent.join(&base);

        let Ok(png_meta_text) = fs::read_to_string(&png_meta_path) else {
            stats.atlases_no_meta += 1;
            continue;
        };
        if is_legacy_texture(&png_meta_text) {
            stats.atlases_legacy += 1;
            continue;
        }
        let prefix = extract_prefix(&tps_meta_path);
        let png_path = parent.join(format!("{base}.png"));

        // Drive the real pipeline (phase 1): this applies the .tps.fab.json /
        // .tps.mesh.json combination, so we compare each *final* emitted sprite
        // (combined geometry and all) against the committed golden — not the raw
        // tpsheet part. `build` reads PPU / atlas GUID / existing-meta GUIDs
        // itself and writes nothing.
        let plan = match pipeline::build(&GenerateInputs {
            tpsheet_path,
            tps_path: &tps_path,
            atlas_png_path: &png_path,
            sprite_dir: &sprite_dir,
            prefix: &prefix,
        }) {
            Ok(p) => p,
            Err(e) => {
                stats.atlases_parse_failed += 1;
                stats.parse_failures.push((tpsheet_path.clone(), format!("build: {e}")));
                continue;
            }
        };

        let atlas_label = parent
            .strip_prefix(&assets_root)
            .map(|p| p.join(&base).to_string_lossy().into_owned())
            .unwrap_or_else(|_| base.clone());

        // `plan.writes` is the final emitted output: `.asset` + `.asset.meta`
        // for every sprite (combined sprites/meshes included), plus the atlas
        // `.png.meta` when alphaIsTransparency would change. Compare each
        // against the committed golden at the same path.
        for (path, bytes) in &plan.writes {
            let ps = path.to_string_lossy();
            let is_meta = ps.ends_with(".asset.meta");
            if !is_meta && !ps.ends_with(".asset") {
                continue; // atlas .png.meta — not a per-sprite golden
            }
            let name = path.file_stem().unwrap().to_string_lossy().into_owned();
            let Ok(golden) = fs::read(path) else {
                stats.sprites_missing_golden += 1;
                continue;
            };

            if is_meta {
                if *bytes != golden {
                    stats.sprites_mismatch_meta += 1;
                    if stats.sprites_mismatch_meta <= 3 {
                        // Metas only carry GUID variation; dump the diff window.
                        let off = first_diff_offset(bytes, &golden);
                        let lo = off.saturating_sub(8);
                        let hi_g = (off + 24).min(bytes.len());
                        let hi_e = (off + 24).min(golden.len());
                        eprintln!(
                            "  META DIFF {} :: {name}\n    generated[{lo}..{hi_g}]: {:?}\n    golden   [{lo}..{hi_e}]: {:?}",
                            tpsheet_path.display(),
                            String::from_utf8_lossy(&bytes[lo..hi_g]),
                            String::from_utf8_lossy(&golden[lo..hi_e]),
                        );
                    }
                }
                continue;
            }

            stats.sprites_compared += 1;
            if *bytes == golden {
                stats.sprites_byte_exact += 1;
            } else {
                stats.sprites_mismatch_asset += 1;
                if first_mismatches.len() < 12 {
                    first_mismatches.push((
                        tpsheet_path.clone(),
                        name,
                        "asset",
                        first_diff_offset(bytes, &golden),
                    ));
                }
                *stats.drift_atlases.entry(atlas_label.clone()).or_insert(0) += 1;
            }
        }
    }

    eprintln!();
    eprintln!("=== meow-tower e2e parity report ===");
    eprintln!("atlases scanned:        {}", stats.atlases_total);
    eprintln!("  legacy (skipped):     {}", stats.atlases_legacy);
    eprintln!("  no .png.meta:         {}", stats.atlases_no_meta);
    eprintln!("  parse failed:         {}", stats.atlases_parse_failed);
    for (p, why) in &stats.parse_failures {
        eprintln!("    {} — {why}", p.display());
    }
    eprintln!("sprites compared:       {}", stats.sprites_compared);
    eprintln!("  byte-exact:           {}", stats.sprites_byte_exact);
    eprintln!("  mismatch (.asset):    {}", stats.sprites_mismatch_asset);
    eprintln!("  mismatch (.meta):     {}", stats.sprites_mismatch_meta);
    eprintln!("  golden missing:       {}", stats.sprites_missing_golden);
    eprintln!("drift atlases:          {}", stats.drift_atlases.len());
    for (atlas, n) in stats.drift_atlases.iter().take(10) {
        eprintln!("  {n:>4} mismatches  {atlas}");
    }
    if stats.drift_atlases.len() > 10 {
        eprintln!("  ... ({} more)", stats.drift_atlases.len() - 10);
    }
    for (path, name, kind, off) in first_mismatches.iter().take(8) {
        eprintln!(
            "  first divergence  {kind} @{off:<6}  {} :: {name}",
            path.display()
        );
    }
    eprintln!();

    // Hard parity gates. Anything outside the explicit allowlist below
    // counts as a regression. Allowlist owners: when the underlying gap
    // is fixed, remove the entry — the test will fail until it's gone,
    // forcing a confirmation.
    assert_eq!(stats.atlases_parse_failed, 0, "tpsheet/tps parse failures");
    assert!(
        stats.sprites_compared > 0,
        "no sprites compared — fixture path wrong?"
    );

    // 100% parity reached. Any future divergence is a regression.
    const ALLOWED_ASSET_MISMATCHES: usize = 0;
    const ALLOWED_META_MISMATCHES: usize = 0;
    assert_eq!(
        stats.sprites_mismatch_asset, ALLOWED_ASSET_MISMATCHES,
        ".asset mismatches changed (allowed {ALLOWED_ASSET_MISMATCHES}); regression or progress — \
         update the constant after auditing"
    );
    assert_eq!(
        stats.sprites_mismatch_meta, ALLOWED_META_MISMATCHES,
        ".meta mismatches changed (allowed {ALLOWED_META_MISMATCHES})"
    );
}
